#!/bin/sh

### Grab stuff from GBBOpen
result=""
curl --silent "http://gbbopen.org/svn/GBBopen/trunk/source/tools/portable-threads.lisp" \
 > portable-threads.lisp
result="$? $result"
curl --silent "http://gbbopen.org/svn/GBBopen/trunk/LICENSE" > "LICENSE"
result="$? $result"
curl --silent "http://gbbopen.org/svn/GBBopen/trunk/COPYING" > "COPYING"
result="$? $result"
if [ "$result" != "0 0 0 " ]; then
    echo "failed to get data: " $result
    exit -1
fi

### Put it in darcs
darcs whats --summ --look
if [ $? -ne 0 ]; then
	echo "No changes to record"
else
	darcs record -a -m "Recording latest changes from GBBOpen"

	### Now we can proceed in the usual fashion
	make-1-asdf-package "portable-threads" "portable-threads"
	rsync-1-repository  "portable-threads" "portable-threads"
fi

